### PR TITLE
 JSON methods, toJSON

### PR DESCRIPTION
**Pull request by engag1ng**

### CODE REVIEW

**Comment by iliakan** [comment]
I guess, there's no maintainer for this translation.

Do you want to become one?

**Comment by engag1ng** [comment]
Hi, sure :)

**Comment by iliakan** [comment]
Invited! Re-created the readme.md as well )

**Comment by engag1ng** [comment]
Thank you. When you have time, can you give me a quick introduction of how to manage all the stuff. Thanks.

**Comment by engag1ng** [comment]
> Invited! Re-created the readme.md as well )

Where can I accept the invite, please?

**Comment by iliakan** [comment]
On your email... Or here? https://github.com/javascript-tutorial/de.javascript.info/invitations

**Comment by engag1ng** [comment]
No, it's not there. Idk. I can review pull requests, but I can't merge them.

**Comment by iliakan** [comment]
image

**Comment by engag1ng** [comment]
Got it. It was under organizations. Thanks :)

**Pull request closed without merging**
